#!/usr/bin/env bash
## This script runs the 'whoami' command as the user passed as an argument
#
## Check if a username is provided
#if [ -z "$1" ]; then
#  echo "Usage: $0 <username>"
#    exit 1
#    fi
#
#    # Run the whoami command as the specified user
#    sudo -u "$1" whoami
