#!/usr/bin/env bash
#
## Start Apache with sudo
#sudo service apache2 start
#
## Allow write access to /var/www/html
#sudo chmod 777 /var/www/html
#
## Ensure 'Hello Holberton' is returned
#echo "Hello Holberton" | sudo tee /var/www/html/index.html
#
