#!/usr/bin/env bash
# This script installs and configures HAProxy for load balancing

# Install HAProxy
apt update -y
apt install -y haproxy

# Configure HAProxy
echo "frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 44.208.23.228:80 check
    server web-02 18.208.133.144:80 check" > /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
systemctl restart haproxy
