#!/usr/bin/env bash
# Install and start Nginx, and serve "Holberton School"

apt-get update -y
apt-get install nginx -y

# Ensure "Holberton School" is displayed
echo "Holberton School" > /usr/share/nginx/html/index.html

# Start Nginx manually
nginx
