#!/usr/bin/env bash
# Install Nginx and configure it to serve Holberton School

sudo apt update -y
sudo apt install nginx -y

# Add Holberton School to the default index.html page
echo '<html>
<head><title>Holberton School</title></head>
<body>
    <h1>Holberton School for the win!</h1>
</body>
</html>' | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx using service (not systemctl)
sudo service nginx restart
